### ISSUE TITLE
where is auxiliary files

### ISSUE THREAD

**Issue by XuJ** [nju-websoft/CKGG#2]
where is <http://w3id.org/ckgg/1.0/instances/auxiliary/>? Thanks

**Comment by sylxjtu** [comment]
Hi XuJ,

Thanks for your interest in using CKGG! The namespace http://w3id.org/ckgg/1.0/instances/auxiliary/ contains auxiliary entities such as timezones and climate types. You can get the data from [zenodo](https://zenodo.org/records/4668711). Specifically, the related files are:
* `tz.nt.gz`: metadata of timezones (label, offset to gmt)
* `tz_loc.nt.gz`: timezone of locations
* `climate.nt.gz`: climate type of location, also metadata about climate types (name, description, polygon)
* `ocean_current.nt.gz`: influenced by ocean current, also metadata about ocean currents (name, linestring)

Please let me know if you have further questions.
